import{a as u,A as f,S as m}from"./assets/vendor-5ff3e303.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();u.defaults.headers.common["x-api-key"]="live_jJ5aLGn50ZkM07nMxodxDW7fSjdGGLoPRReFN6eyXEoTBwtctXneqCxESjN80VWx";const d="https://api.thecatapi.com/v1";function p(){return fetch(`${d}/breeds?x-api-key=${f}`).then(e=>{if(e.ok)return e.json();throw new Error(e.statusText)})}function h(e){return fetch(`${d}/images/${e}`).then(o=>{if(o.ok)return o.json();throw new Error(o.statusText)})}const l=document.querySelector(".breed-select"),a=document.querySelector(".cat-info"),i=document.querySelector(".loader");function v(e){return e.map(o=>{const{name:s,reference_image_id:n}=o;return`<option value="${n}">${s}</option>`}).join("")}function y(e){const{url:o,breeds:{0:{description:s,temperament:n,name:t}}}=e;return i.classList.remove("visible"),`<h2>${t}</h2>
  <div class="info-container">
  <img width="500" src="${o}" class="cat-image">
  <div class="text-container">
  <p class="cat-p">${s}</p>
  <p class="cat-p">
  <span class="bold">Temperament: </span>${n}</p>
  </div>
  </div>`}i.classList.add("visible");p().then(e=>{console.log(e),l.innerHTML='<option data-placeholder="true"></option>'+v(e)}).then(()=>{new m({select:"#single",settings:{placeholderText:"Select a cat"},events:{afterChange:()=>{a.classList.add("invisible"),i.classList.remove("invisible"),h(l.value).then(e=>a.innerHTML=y(e)).then(()=>{i.classList.add("invisible"),a.classList.remove("invisible")}).catch(e=>console.error(`Error occurred: ${e}`))}}}),i.classList.add("invisible"),document.getElementById("single").classList.remove("invisible")}).catch(e=>console.error(`Error occurred: ${e}`));
//# sourceMappingURL=commonHelpers.js.map
