import{a as u,S as p,i as f}from"./assets/vendor-12004871.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerpolicy&&(n.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?n.credentials="include":t.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function o(t){if(t.ep)return;t.ep=!0;const n=i(t);fetch(t.href,n)}})();const m="live_jJ5aLGn50ZkM07nMxodxDW7fSjdGGLoPRReFN6eyXEoTBwtctXneqCxESjN80VWx",h="https://api.thecatapi.com/v1",d=u.create({baseURL:h,headers:{"x-api-key":m,"Content-Type":"application/json"}});function g(){return d.get("/breeds").then(e=>e.data).catch(e=>(console.error(`Error fetching breeds: ${e}`),Promise.resolve([])))}function v(e){return d.get(`/images/${e}`).then(r=>r.data).catch(r=>{throw new Error(r.response.statusText)})}const c=document.querySelector(".breed-select"),l=document.querySelector(".cat-info"),s=document.querySelector(".loader");function y(e){return e.map(r=>{const{name:i,reference_image_id:o}=r;return`<option value="${o}">${i}</option>`}).join("")}function L(e){const{url:r,breeds:{0:{description:i,temperament:o,name:t}}}=e;return s.classList.remove("visible"),`<h2>${t}</h2>
  <div class="info-container">
  <img width="500" src="${r}" class="cat-image">
  <div class="text-container">
  <p class="cat-p">${i}</p>
  <p class="cat-p">
  <span class="bold">Temperament: </span>${o}</p>
  </div>
  </div>`}s.classList.add("visible");g().then(e=>{Array.isArray(e)&&e.length>0?c.innerHTML='<option data-placeholder="true"></option>'+y(e):c.innerHTML=""}).then(()=>{new p({select:"#single",settings:{placeholderText:"Select a cat"},events:{afterChange:()=>{l.classList.add("invisible"),s.classList.remove("invisible"),v(c.value).then(e=>l.innerHTML=L(e)).then(()=>{s.classList.add("invisible"),l.classList.remove("invisible")}).catch(e=>console.error(`Error occurred: ${e}`))}}}),s.classList.add("invisible"),document.getElementById("single").classList.remove("invisible")}).catch(e=>{s.classList.add("invisible"),console.error(`Error occurred: ${e}`),c.innerHTML="<option>Error loading breeds. Please try again later.</option>",f.error({title:"Error!",message:"Oops! Something went wrong while loading breeds.",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
